#Importamos librerias
import ModuloCONAGUA

ModuloCONAGUA.proceso("TACUBAYA","TACUBAYA")   

ModuloCONAGUA.proceso("ECOGUARDAS","ECOGUARDAS")

ModuloCONAGUA.proceso("TEZONTLE","TEZONTLE")

ModuloCONAGUA.proceso("CERROCATEDRAL","ISI")

ModuloCONAGUA.proceso("ALTZOMONI","ALTZOMONI")

ModuloCONAGUA.proceso("PRESAMADINSMN","NAU")

ModuloCONAGUA.proceso("ESCNALCIENCIASBIOLOGICAS","ENCB")